///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Mercy_Browserstack
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Mercy_BrowserstackRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("80c48ebb-f022-4822-bb1c-8c7f17a1c030")]
    public partial class Mercy_BrowserstackRepository : RepoGenBaseFolder
    {
        static Mercy_BrowserstackRepository instance = new Mercy_BrowserstackRepository();
        Mercy_BrowserstackRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        Mercy_BrowserstackRepositoryFolders.ExplorerAppFolder _explorer;
        Mercy_BrowserstackRepositoryFolders.TheInternetGoogleChromeAppFolder _theinternetgooglechrome;

        /// <summary>
        /// Gets the singleton class instance representing the Mercy_BrowserstackRepository element repository.
        /// </summary>
        [RepositoryFolder("80c48ebb-f022-4822-bb1c-8c7f17a1c030")]
        public static Mercy_BrowserstackRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Mercy_BrowserstackRepository() 
            : base("Mercy_BrowserstackRepository", "/", null, 0, false, "80c48ebb-f022-4822-bb1c-8c7f17a1c030", ".\\RepositoryImages\\Mercy_BrowserstackRepository80c48ebb.rximgres")
        {
            _applicationundertest = new Mercy_BrowserstackRepositoryFolders.ApplicationUnderTestAppFolder(this);
            _explorer = new Mercy_BrowserstackRepositoryFolders.ExplorerAppFolder(this);
            _theinternetgooglechrome = new Mercy_BrowserstackRepositoryFolders.TheInternetGoogleChromeAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("80c48ebb-f022-4822-bb1c-8c7f17a1c030")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("c89c83a4-f72f-4e48-be61-976efb045439")]
        public virtual Mercy_BrowserstackRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The Explorer folder.
        /// </summary>
        [RepositoryFolder("6f2a67f9-0cb9-466c-807e-08e64655b53d")]
        public virtual Mercy_BrowserstackRepositoryFolders.ExplorerAppFolder Explorer
        {
            get { return _explorer; }
        }

        /// <summary>
        /// The TheInternetGoogleChrome folder.
        /// </summary>
        [RepositoryFolder("afe4563d-e2f2-4ab9-af29-c1f8012e72d3")]
        public virtual Mercy_BrowserstackRepositoryFolders.TheInternetGoogleChromeAppFolder TheInternetGoogleChrome
        {
            get { return _theinternetgooglechrome; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class Mercy_BrowserstackRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("c89c83a4-f72f-4e48-be61-976efb045439")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _welcometotheinternetInfo;
            RepoItemInfo _keypressesInfo;
            RepoItemInfo _targetInfo;
            RepoItemInfo _someinputtagInfo;
            RepoItemInfo _somebodytagInfo;
            RepoItemInfo _flashmessagesInfo;
            RepoItemInfo _somelitagInfo;
            RepoItemInfo _pagefooterInfo;
            RepoItemInfo _exampleInfo;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='the-internet.herokuapp.com']", parentFolder, 30000, null, false, "c89c83a4-f72f-4e48-be61-976efb045439", "")
            {
                _welcometotheinternetInfo = new RepoItemInfo(this, "WelcomeToTheInternet", ".//div[#'content']/h1[@innertext='Welcome to the-internet']", "", 30000, null, "04fb33cc-b343-4d9b-850c-c35a5311e535");
                _keypressesInfo = new RepoItemInfo(this, "KeyPresses", ".//div[#'content']//a[@innertext='Key Presses']", "", 30000, null, "173ec8ea-468c-4df8-a92b-1026a7e47b86");
                _targetInfo = new RepoItemInfo(this, "Target", ".//input[#'target']", "", 30000, null, "0ca9c65d-3ee8-4aa2-b457-06e1c24187ae");
                _someinputtagInfo = new RepoItemInfo(this, "SomeInputTag", "body//form/input", "", 30000, null, "3b028a1f-9f94-4bd7-a5ce-0242d4d6956d");
                _somebodytagInfo = new RepoItemInfo(this, "SomeBodyTag", "body", "", 30000, null, "4d6be675-7f86-497b-a82f-8fec29c51c52");
                _flashmessagesInfo = new RepoItemInfo(this, "FlashMessages", ".//div[#'flash-messages']", "", 30000, null, "8e81ac9e-e82c-43c3-82ea-299c6ce8565c");
                _somelitagInfo = new RepoItemInfo(this, "SomeLiTag", ".//div[#'content']/ul/li[15]", "", 30000, null, "9852591d-f0e0-4716-8831-0a4e1125f810");
                _pagefooterInfo = new RepoItemInfo(this, "PageFooter", ".//div[#'page-footer']", "", 30000, null, "81a6f72e-35cb-4bca-8e74-71db1b104b4b");
                _exampleInfo = new RepoItemInfo(this, "Example", ".//div[#'content']/div", "", 30000, null, "b9517361-4ce4-45fe-8516-285004474282");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("c89c83a4-f72f-4e48-be61-976efb045439")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("c89c83a4-f72f-4e48-be61-976efb045439")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The WelcomeToTheInternet item.
            /// </summary>
            [RepositoryItem("04fb33cc-b343-4d9b-850c-c35a5311e535")]
            public virtual Ranorex.H1Tag WelcomeToTheInternet
            {
                get
                {
                    return _welcometotheinternetInfo.CreateAdapter<Ranorex.H1Tag>(true);
                }
            }

            /// <summary>
            /// The WelcomeToTheInternet item info.
            /// </summary>
            [RepositoryItemInfo("04fb33cc-b343-4d9b-850c-c35a5311e535")]
            public virtual RepoItemInfo WelcomeToTheInternetInfo
            {
                get
                {
                    return _welcometotheinternetInfo;
                }
            }

            /// <summary>
            /// The KeyPresses item.
            /// </summary>
            [RepositoryItem("173ec8ea-468c-4df8-a92b-1026a7e47b86")]
            public virtual Ranorex.ATag KeyPresses
            {
                get
                {
                    return _keypressesInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The KeyPresses item info.
            /// </summary>
            [RepositoryItemInfo("173ec8ea-468c-4df8-a92b-1026a7e47b86")]
            public virtual RepoItemInfo KeyPressesInfo
            {
                get
                {
                    return _keypressesInfo;
                }
            }

            /// <summary>
            /// The Target item.
            /// </summary>
            [RepositoryItem("0ca9c65d-3ee8-4aa2-b457-06e1c24187ae")]
            public virtual Ranorex.InputTag Target
            {
                get
                {
                    return _targetInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Target item info.
            /// </summary>
            [RepositoryItemInfo("0ca9c65d-3ee8-4aa2-b457-06e1c24187ae")]
            public virtual RepoItemInfo TargetInfo
            {
                get
                {
                    return _targetInfo;
                }
            }

            /// <summary>
            /// The SomeInputTag item.
            /// </summary>
            [RepositoryItem("3b028a1f-9f94-4bd7-a5ce-0242d4d6956d")]
            public virtual Ranorex.InputTag SomeInputTag
            {
                get
                {
                    return _someinputtagInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The SomeInputTag item info.
            /// </summary>
            [RepositoryItemInfo("3b028a1f-9f94-4bd7-a5ce-0242d4d6956d")]
            public virtual RepoItemInfo SomeInputTagInfo
            {
                get
                {
                    return _someinputtagInfo;
                }
            }

            /// <summary>
            /// The SomeBodyTag item.
            /// </summary>
            [RepositoryItem("4d6be675-7f86-497b-a82f-8fec29c51c52")]
            public virtual Ranorex.BodyTag SomeBodyTag
            {
                get
                {
                    return _somebodytagInfo.CreateAdapter<Ranorex.BodyTag>(true);
                }
            }

            /// <summary>
            /// The SomeBodyTag item info.
            /// </summary>
            [RepositoryItemInfo("4d6be675-7f86-497b-a82f-8fec29c51c52")]
            public virtual RepoItemInfo SomeBodyTagInfo
            {
                get
                {
                    return _somebodytagInfo;
                }
            }

            /// <summary>
            /// The FlashMessages item.
            /// </summary>
            [RepositoryItem("8e81ac9e-e82c-43c3-82ea-299c6ce8565c")]
            public virtual Ranorex.DivTag FlashMessages
            {
                get
                {
                    return _flashmessagesInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The FlashMessages item info.
            /// </summary>
            [RepositoryItemInfo("8e81ac9e-e82c-43c3-82ea-299c6ce8565c")]
            public virtual RepoItemInfo FlashMessagesInfo
            {
                get
                {
                    return _flashmessagesInfo;
                }
            }

            /// <summary>
            /// The SomeLiTag item.
            /// </summary>
            [RepositoryItem("9852591d-f0e0-4716-8831-0a4e1125f810")]
            public virtual Ranorex.LiTag SomeLiTag
            {
                get
                {
                    return _somelitagInfo.CreateAdapter<Ranorex.LiTag>(true);
                }
            }

            /// <summary>
            /// The SomeLiTag item info.
            /// </summary>
            [RepositoryItemInfo("9852591d-f0e0-4716-8831-0a4e1125f810")]
            public virtual RepoItemInfo SomeLiTagInfo
            {
                get
                {
                    return _somelitagInfo;
                }
            }

            /// <summary>
            /// The PageFooter item.
            /// </summary>
            [RepositoryItem("81a6f72e-35cb-4bca-8e74-71db1b104b4b")]
            public virtual Ranorex.DivTag PageFooter
            {
                get
                {
                    return _pagefooterInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The PageFooter item info.
            /// </summary>
            [RepositoryItemInfo("81a6f72e-35cb-4bca-8e74-71db1b104b4b")]
            public virtual RepoItemInfo PageFooterInfo
            {
                get
                {
                    return _pagefooterInfo;
                }
            }

            /// <summary>
            /// The Example item.
            /// </summary>
            [RepositoryItem("b9517361-4ce4-45fe-8516-285004474282")]
            public virtual Ranorex.DivTag Example
            {
                get
                {
                    return _exampleInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Example item info.
            /// </summary>
            [RepositoryItemInfo("b9517361-4ce4-45fe-8516-285004474282")]
            public virtual RepoItemInfo ExampleInfo
            {
                get
                {
                    return _exampleInfo;
                }
            }
        }

        /// <summary>
        /// The ExplorerAppFolder folder.
        /// </summary>
        [RepositoryFolder("6f2a67f9-0cb9-466c-807e-08e64655b53d")]
        public partial class ExplorerAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _googlechrome1runningwindowInfo;

            /// <summary>
            /// Creates a new Explorer  folder.
            /// </summary>
            public ExplorerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Explorer", "/menubar[@processname='explorer']", parentFolder, 30000, null, true, "6f2a67f9-0cb9-466c-807e-08e64655b53d", "")
            {
                _googlechrome1runningwindowInfo = new RepoItemInfo(this, "GoogleChrome1RunningWindow", "container[@controlid='40965']//toolbar[@accessiblename='Running applications']/button[6]", "", 30000, null, "f68e0df5-b545-4671-9dc8-1e8e331c3aa4");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("6f2a67f9-0cb9-466c-807e-08e64655b53d")]
            public virtual Ranorex.MenuBar Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.MenuBar>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("6f2a67f9-0cb9-466c-807e-08e64655b53d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The GoogleChrome1RunningWindow item.
            /// </summary>
            [RepositoryItem("f68e0df5-b545-4671-9dc8-1e8e331c3aa4")]
            public virtual Ranorex.Button GoogleChrome1RunningWindow
            {
                get
                {
                    return _googlechrome1runningwindowInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The GoogleChrome1RunningWindow item info.
            /// </summary>
            [RepositoryItemInfo("f68e0df5-b545-4671-9dc8-1e8e331c3aa4")]
            public virtual RepoItemInfo GoogleChrome1RunningWindowInfo
            {
                get
                {
                    return _googlechrome1runningwindowInfo;
                }
            }
        }

        /// <summary>
        /// The TheInternetGoogleChromeAppFolder folder.
        /// </summary>
        [RepositoryFolder("afe4563d-e2f2-4ab9-af29-c1f8012e72d3")]
        public partial class TheInternetGoogleChromeAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _backInfo;
            RepoItemInfo _theinternetInfo;
            RepoItemInfo _addressandsearchbarInfo;

            /// <summary>
            /// Creates a new TheInternetGoogleChrome  folder.
            /// </summary>
            public TheInternetGoogleChromeAppFolder(RepoGenBaseFolder parentFolder) :
                    base("TheInternetGoogleChrome", "/form[@title>'The Internet - Google Chr']", parentFolder, 30000, null, true, "afe4563d-e2f2-4ab9-af29-c1f8012e72d3", "")
            {
                _backInfo = new RepoItemInfo(this, "Back", "container[@accessiblename>'The Internet - Google Chr']/container[@accessiblename='Google Chrome']//toolbar[@accessiblerole='ToolBar']/button[@accessiblename='Back']", "", 30000, null, "426866ae-c43a-499b-a37b-d7ac1e51253b");
                _theinternetInfo = new RepoItemInfo(this, "TheInternet", "container[@accessiblename>'Top Downloads - Google Ch']/container[@accessiblename='Google Chrome']//tabpagelist/container[1]/tabpage[@accessiblename='The Internet']", "", 30000, null, "8be55beb-872c-4c8a-b431-8890c3d73864");
                _addressandsearchbarInfo = new RepoItemInfo(this, "AddressAndSearchBar", "container[@accessiblename>'The Internet - Google Chr']/container[@accessiblename='Google Chrome']//toolbar[@accessiblerole='ToolBar']/?/?/text[@accessiblename='Address and search bar']", "", 30000, null, "397d533d-3351-4304-b37f-4d47a47ab4af");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("afe4563d-e2f2-4ab9-af29-c1f8012e72d3")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("afe4563d-e2f2-4ab9-af29-c1f8012e72d3")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Back item.
            /// </summary>
            [RepositoryItem("426866ae-c43a-499b-a37b-d7ac1e51253b")]
            public virtual Ranorex.Button Back
            {
                get
                {
                    return _backInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Back item info.
            /// </summary>
            [RepositoryItemInfo("426866ae-c43a-499b-a37b-d7ac1e51253b")]
            public virtual RepoItemInfo BackInfo
            {
                get
                {
                    return _backInfo;
                }
            }

            /// <summary>
            /// The TheInternet item.
            /// </summary>
            [RepositoryItem("8be55beb-872c-4c8a-b431-8890c3d73864")]
            public virtual Ranorex.TabPage TheInternet
            {
                get
                {
                    return _theinternetInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The TheInternet item info.
            /// </summary>
            [RepositoryItemInfo("8be55beb-872c-4c8a-b431-8890c3d73864")]
            public virtual RepoItemInfo TheInternetInfo
            {
                get
                {
                    return _theinternetInfo;
                }
            }

            /// <summary>
            /// The AddressAndSearchBar item.
            /// </summary>
            [RepositoryItem("397d533d-3351-4304-b37f-4d47a47ab4af")]
            public virtual Ranorex.Text AddressAndSearchBar
            {
                get
                {
                    return _addressandsearchbarInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The AddressAndSearchBar item info.
            /// </summary>
            [RepositoryItemInfo("397d533d-3351-4304-b37f-4d47a47ab4af")]
            public virtual RepoItemInfo AddressAndSearchBarInfo
            {
                get
                {
                    return _addressandsearchbarInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
